### ISSUE TITLE
Bug - 2.10.0 - Chrome version must be >= 53.0.2785.0

### ISSUE THREAD

**Issue by danielmenezesbr** [fhoeben/hsac-fitnesse-fixtures#104]
1) Start hsac-fitnesse-fixtures 2.10.0 on Windows: java -jar fitnesse-standalone.jar

2) Go http://localhost/HsacExamples.SlimTests.BrowserTests.AngularJsCalculatorTest?test

Result:
```
__EXCEPTION__:org.openqa.selenium.WebDriverException: unknown error: Chrome version must be >= 53.0.2785.0
  (Driver info: chromedriver=2.25.426923 (0390b88869384d6eb0d5d09729679f934aab9eed),platform=Windows NT 6.3.9600 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1.06 seconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'myhost', ip: '10.2.2.1', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.chrome.ChromeDriver
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [rt.jar:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [rt.jar:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [rt.jar:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [rt.jar:1.8.0_60]
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206) [selenium-remote-driver-2.53.1.jar]
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158) [selenium-remote-driver-2.53.1.jar]
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678) [selenium-remote-driver-2.53.1.jar]
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:249) [selenium-remote-driver-2.53.1.jar]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131) [selenium-remote-driver-2.53.1.jar]
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144) [selenium-remote-driver-2.53.1.jar]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:170) [selenium-chrome-driver-2.53.1.jar]
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:138) [selenium-chrome-driver-2.53.1.jar]
	at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup$1.createDriver(SeleniumDriverSetup.java:82) [file:/C:/temp/2.10.0/fixtures/]
	at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.driver(SeleniumHelper.java:915) [file:/C:/temp/2.10.0/fixtures/]
	at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.setAndUseDriverFactory(SeleniumDriverSetup.java:406) [file:/C:/temp/2.10.0/fixtures/]
	at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriver(SeleniumDriverSetup.java:95) [file:/C:/temp/2.10.0/fixtures/]
	at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverForWithProfile(SeleniumDriverSetup.java:141) [file:/C:/temp/2.10.0/fixtures/]
	at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverFor(SeleniumDriverSetup.java:170) [file:/C:/temp/2.10.0/fixtures/]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_60]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:147) [fitnesse-standalone.jar:20161106]
	at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:50) [file:/C:/temp/2.10.0/fixtures/]
	at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:30) [file:/C:/temp/2.10.0/fixtures/]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_60]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.methodInvoke(DefaultInteraction.java:147) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.callMethod(DefaultInteraction.java:130) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.invokeMethod(DefaultInteraction.java:114) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.fixtureInteraction.DefaultInteraction.findAndInvoke(DefaultInteraction.java:92) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:130) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:103) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimServer.serve(SlimServer.java:47) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimService.handle(SlimService.java:168) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimService.acceptOne(SlimService.java:176) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimService.accept(SlimService.java:138) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimService.startWithFactory(SlimService.java:91) [fitnesse-standalone.jar:20161106]
	at fitnesse.slim.SlimService.main(SlimService.java:56) [fitnesse-standalone.jar:20161106]
```

PS: It work fine in 2.9.2

**Comment by fhoeben** [comment]
This is because of the chromedriver update in 2.10.0. You will have to either update your Chrome installation to a newer version (53.0.2785.0 or newer according to the message), or downgrade to chromedriver 2.24 (which was included in my baseline 2.9.2)
