### ISSUE TITLE
Exception: The request string is malformed and can not be parsed

### ISSUE THREAD

**Issue by blling** [fhoeben/hsac-fitnesse-fixtures#176]
When running `hsac-fitnesse-fixtures` and edit pages, i always got this exception, anyone knows how to resovle this?
```java
WARNING: An error occured while fulfilling user request [fitnesse.http.HttpException: The request string is malformed and can not be parsed]
java.util.concurrent.ExecutionException: fitnesse.http.HttpException: The request string is malformed and can not be parsed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at fitnesse.FitNesseExpediter.makeResponse(FitNesseExpediter.java:105)
	at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:58)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: fitnesse.http.HttpException: The request string is malformed and can not be parsed
	at fitnesse.http.Request.checkRequestLine(Request.java:159)
	at fitnesse.http.Request.readAndParseRequestLine(Request.java:73)
	at fitnesse.http.Request.parse(Request.java:61)
	at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:102)
	at fitnesse.FitNesseExpediter$1.call(FitNesseExpediter.java:99)
	... 4 more
```

**Comment by fhoeben** [comment]
I have seen this error, but for me it doesn't always occur when I edit a page via the wiki. Do you have a sequence of steps that will always trigger the problem?

I believe it is an issue in the fitnesse project itself. See also https://github.com/unclebob/fitnesse/issues/1042 or https://github.com/unclebob/fitnesse/issues/981

**Comment by blling** [comment]
Sorry for late. it seem good now and i can not reproduce it.
