### ISSUE TITLE
Unable to get response from http / json test

### ISSUE THREAD

**Issue by MelvinKlh** [fhoeben/hsac-fitnesse-fixtures#259]
In my project we run into an issue with SOAP and JSON tests. Internal and external endpoints don't return a response, whether it is SOAP or JSON. If I execute the same, with for example SOAPUI, I get a response. Also i'm able to open JSON message from the endpoint in my browser. When running the test in Debug mode I get this error 
`Could not complete testing: fitnesse.slim.SlimError: Error connecting to SLiM server on localhost:53807Unable to start test system 'slim': fitnesse.slim.SlimError: Error connecting to SLiM server on localhost:53807`

Execution log message:
`Standard Output:
Listening for transport dt_socket at address: 8000`

`Internal Exception:
Error connecting to SLiM server on localhost:53807`

I've set the `slim.port` to 0 and use slim as TEST_SYSTEM. Enabling and disabling SSL didn't help and http or https doesn't make any difference. Also changed the `slim.port` to a fixed value, but same error came up. I only have the issue when using HTTP or JSON test, Browser test work fine.

It might be that something in the network blocks something, but I can't really pinpoint what exactly the issue is. Do you, or someone else, have any idea what is causing the issue or where to look at? Below the full stacktrace.

Thanks. 

**Stacktrace:**
`__EXCEPTION__:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Unable to GET response from: http://jsonplaceholder.typicode.com/posts
at nl.hsac.fitnesse.fixture.slim.HttpTest.getImpl(HttpTest.java:423) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.HttpTest.getFrom(HttpTest.java:397) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:61) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:41) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:239) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:223) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:185) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.serve(SlimServer.java:47) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20190224]
Caused by: java.lang.RuntimeException: Unable to get response from: http://jsonplaceholder.typicode.com/posts
at nl.hsac.fitnesse.fixture.util.HttpClient.getResponse(HttpClient.java:294) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.util.HttpClient.get(HttpClient.java:148) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.Environment.doGet(Environment.java:380) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.HttpTest.getImpl(HttpTest.java:421) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.HttpTest.getFrom(HttpTest.java:397) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:61) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:41) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:239) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:223) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:185) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.serve(SlimServer.java:47) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20190224]
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to jsonplaceholder.typicode.com:80 [jsonplaceholder.typicode.com/104.28.2.245, jsonplaceholder.typicode.com/104.28.3.245] failed: Connection timed out: connect
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) [httpclient-4.5.7.jar:4.5.7]
at nl.hsac.fitnesse.fixture.util.HttpClient.executeMethod(HttpClient.java:326) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.util.HttpClient.getResponse(HttpClient.java:289) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.util.HttpClient.get(HttpClient.java:148) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.Environment.doGet(Environment.java:380) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.HttpTest.getImpl(HttpTest.java:421) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.HttpTest.getFrom(HttpTest.java:397) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:61) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:41) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:239) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:223) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:185) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.serve(SlimServer.java:47) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20190224]
Caused by: java.net.ConnectException: Connection timed out: connect
at java.net.DualStackPlainSocketImpl.connect0(Native Method) [rt.jar:1.8.0_201]
at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79) [rt.jar:1.8.0_201]
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) [rt.jar:1.8.0_201]
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) [rt.jar:1.8.0_201]
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) [rt.jar:1.8.0_201]
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) [rt.jar:1.8.0_201]
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) [rt.jar:1.8.0_201]
at java.net.Socket.connect(Socket.java:589) [rt.jar:1.8.0_201]
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) [httpclient-4.5.7.jar:4.5.7]
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) [httpclient-4.5.7.jar:4.5.7]
at nl.hsac.fitnesse.fixture.util.HttpClient.executeMethod(HttpClient.java:326) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.util.HttpClient.getResponse(HttpClient.java:289) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.util.HttpClient.get(HttpClient.java:148) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.Environment.doGet(Environment.java:380) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.HttpTest.getImpl(HttpTest.java:421) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.HttpTest.getFrom(HttpTest.java:397) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:61) [hsac-fitnesse-fixtures-4.3.0.jar]
at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:41) [hsac-fitnesse-fixtures-4.3.0.jar]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_201]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_201]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_201]
at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_201]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:256) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:239) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:223) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:185) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.CallInstruction.executeInternal(CallInstruction.java:35) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimServer.serve(SlimServer.java:47) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20190224]
at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20190224]`

**Comment by fhoeben** [comment]
I've never seen this before, or the error when debugging.
You can try to address the debug issue by completely removing the `!define slim.port ` line from the wiki. There seems to be a problem to connect from your IDE debug Java process itself via a port. Do you have a local firewall restricting network access by/to java processes?

For the actual issue:
I don't know what is happening, and don't have time to try the host you use myself, but I'm surprised to  see `Connect to jsonplaceholder.typicode.com:80 [jsonplaceholder.typicode.com/104.28.2.245, jsonplaceholder.typicode.com/104.28.3.245] failed`. There seem to be two IP addresses.

What happens if you use one of the IPs instead of the hostname?

**Comment by MelvinKlh** [comment]
Unfortunately, removing `!define slim.port` or calling the IP addreses didn't work. I do get the same stracktrace message when calling an internal system, I don't get an IP address in that stacktrace. 

It's higly possible that a firewall is restricting something, since network and VDI's are pretty restricted. I'll have ask around here whether java processes are restricted. 

Just wondering why the error doesn't come up for Browser test? Is it because of the webdriver that is inbetween?

**Comment by fhoeben** [comment]
Yes that is the difference. For BrowserTest your JVM connects to the browser process (wonder why that does work) and the browser's process connects to the remote host. For HttpTest (and its subclasses) the JVM itself connects to the remote host.

**Comment by MelvinKlh** [comment]
Ahh, thanks for explaning and help. I'll see if I can find some people here that can help me solve it as I think it's more related to network restrictions here then HSAC. I will close this thread.
