### ISSUE TITLE
string fixture complex json path error

### ISSUE THREAD

**Issue by eggShellGalore** [fhoeben/hsac-fitnesse-fixtures#265]
tried setting the value of an object by utilizing complex json path via string fixture, but an error was returned by the fitnesse. 

**error:**
```
__EXCEPTION__:java.lang.RuntimeException: $.sampleComplexJSon.labs[?(@.name=='BUN')].location returns multiple results, not a single.
	at nl.hsac.fitnesse.fixture.util.JsonPathHelper.getJsonPath(JsonPathHelper.java:36) [file:/C:/dpm_MLI/main/fixtures/]
	at nl.hsac.fitnesse.fixture.slim.StringFixture.jsonPathAsString(StringFixture.java:51) [file:/C:/dpm_MLI/main/fixtures/] .....
```

**json path:**
`$.sampleComplexJSon.labs[?(@.name=='BUN')].location`

**fitnesse script:**
```
|script|string fixture|
|$saveValue=|json|$sampleJson|path as string|$.sampleComplexJSon.labs[?(@.name=='BUN')].location|
```

**sample complex json object:**
```
{sampleComplexJSon:{"medications":[{"aceInhibitors":[{"name":"lisinopril","strength":"10 mg Tab","dose":"1 tab","route":"PO","sig":"daily","pillCount":"#90","refills":"Refill 3"}],"antianginal":[{"name":"nitroglycerin","strength":"0.4 mg Sublingual Tab","dose":"1 tab","route":"SL","sig":"q15min PRN","pillCount":"#30","refills":"Refill 1"}],"anticoagulants":[{"name":"warfarin sodium","strength":"3 mg Tab","dose":"1 tab","route":"PO","sig":"daily","pillCount":"#90","refills":"Refill 3"}],"betaBlocker":[{"name":"metoprolol tartrate","strength":"25 mg Tab","dose":"1 tab","route":"PO","sig":"daily","pillCount":"#90","refills":"Refill 3"}],"diuretic":[{"name":"furosemide","strength":"40 mg Tab","dose":"1 tab","route":"PO","sig":"daily","pillCount":"#90","refills":"Refill 3"}],"mineral":[{"name":"potassium chloride ER","strength":"10 mEq Tab","dose":"1 tab","route":"PO","sig":"daily","pillCount":"#90","refills":"Refill 3"}]}],"labs":[{"name":"Arterial Blood Gas","time":"Today","location":"Main Hospital Lab"},{"name":"BMP","time":"Today","location":"Primary Care Clinic"},{"name":"BNP","time":"3 Weeks","location":"Primary Care Clinic"},{"name":"BUN","time":"1 Year","location":"Primary Care Clinic"},{"name":"Cardiac Enzymes","time":"Today","location":"Primary Care Clinic"},{"name":"CBC","time":"1 Year","location":"Primary Care Clinic"},{"name":"Creatinine","time":"1 Year","location":"Main Hospital Lab"},{"name":"Electrolyte Panel","time":"1 Year","location":"Primary Care Clinic"},{"name":"Glucose","time":"1 Year","location":"Main Hospital Lab"},{"name":"PT/INR","time":"3 Weeks","location":"Primary Care Clinic"},{"name":"PTT","time":"3 Weeks","location":"Coumadin Clinic"},{"name":"TSH","time":"1 Year","location":"Primary Care Clinic"}],"imaging":[{"name":"Chest X-Ray","time":"Today","location":"Main Hospital Radiology"},{"name":"Chest X-Ray","time":"Today","location":"Main Hospital Radiology"},{"name":"Chest X-Ray","time":"Today","location":"Main Hospital Radiology"}]}}
```

**Comment by tcnh** [comment]
See https://github.com/fhoeben/hsac-fitnesse-fixtures/pull/254

**Comment by eggShellGalore** [comment]
is there a possibility in the future wherein we'll be able to get those value/s and be set on a variable?

**Comment by tcnh** [comment]
There is no json path as string methodin string fixture.. are you using some sort of own implementation?

You can already achieve what you want, as described in #254

```
|script     |json fixture                                                              |
|load       |$sampleJson                                                               |
|$saveValue=|element|0|of json path|$.sampleComplexJSon.labs[?(@.name=='BUN')].location|
```

**Comment by eggShellGalore** [comment]
Thanks for the prompt response
Satisfied with the work around.
