### ISSUE TITLE
SocketException when using latest FitNesse/HSAC-fixtures with hub

### ISSUE THREAD

**Issue by reators** [fhoeben/hsac-fitnesse-fixtures#310]
Hi,
I have an issue with SocketException when using latest FitNesse `20200205` and HSAC `4.11.0` and doing the test using a Selenium-Hub (which is updated to latest version) in an OpenShift/Docker environment:
A test run stops with `SocketException: Broken pipe (Write failed)`

<details>
   <summary>Console log output</summary>

```
Starting FitNesse on port: 8080
Test system terminated with exception [java.net.SocketException: Broken pipe (Write failed)]
SEVERE: Exception rendering #parse(testPage.vm) at skeleton.vm[line 84, column 4] [Broken pipe (Write failed)]
java.net.SocketException: Broken pipe (Write failed)
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at fitnesse.FitNesseExpediter.send(FitNesseExpediter.java:63)
	at fitnesse.http.ChunkedResponse.add(ChunkedResponse.java:60)
	at fitnesse.http.ChunkedResponse.add(ChunkedResponse.java:45)
	at fitnesse.http.ChunkedResponse$1.write(ChunkedResponse.java:129)
	at org.apache.velocity.runtime.parser.node.ASTText.render(ASTText.java:106)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:377)
	at org.apache.velocity.runtime.directive.Parse.render(Parse.java:279)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:295)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:377)
	at org.apache.velocity.Template.merge(Template.java:359)
	at org.apache.velocity.Template.merge(Template.java:264)
	at fitnesse.html.template.HtmlPage.render(HtmlPage.java:83)
	at fitnesse.responders.run.SuiteResponder.doSending(SuiteResponder.java:126)
	at fitnesse.responders.ChunkingResponder.startSending(ChunkingResponder.java:74)
	at fitnesse.http.ChunkedResponse.sendTo(ChunkedResponse.java:29)
	at fitnesse.FitNesseExpediter.sendResponse(FitNesseExpediter.java:86)
	at fitnesse.FitNesseExpediter.run(FitNesseExpediter.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
</details>

Before the upgrade to this version I used FitNesse `20190628` and HSAC `4.8.4` and found that exactly this error happens only when using FitNesses's scenarios. So I thought it's related to them. But now with above versions the same error occurs even without using scenarios.
My little test for the application under test looks like:

<details>
   <summary>mytest.wiki</summary>

```
|Import                           |
|nl.hsac.fitnesse.fixture.slim    |
|nl.hsac.fitnesse.fixture.slim.web|

!***>  Basic settings
!define slim.port {0}
!define TEST_SYSTEM {slim}

Class path
!path fixtures
!path fixtures/*.jar
*!

!define GRID_HUB {https://selenium-hub.example.de/wd/hub}

|script               |selenium driver setup|
|connect to driver for|chrome|at|${GRID_HUB}|

|script|browser test            |
|open  |https://myapp.example.de|
|check |page title   |Myapp-UI  |

|script|selenium driver setup|
|stop driver                 |
```
</details>

What can I do? Downgrade versions until the problem disappears (smells like that ...)?
Thanks in advance for any hints.

**Comment by fhoeben** [comment]
I recognise the stack trace in the console, I get the same the same output each time I navigate directly to a test or suite page (e.g. I enter http://localhost:8001/FitNesse.SuiteAcceptanceTests?suite directly in the address bar). BUT this is not a problem for the test, it is executed normally and I see its result in my browser. When I refresh/reload that page the test is executed again but this time without showing the error in the console.

What I believe this is is an extra request the browser does, and then drops before it gets a full response. And FitNesse logs the error that it could not complete writing to the browser.

So as far as I'm aware this broken pipe does not affect your test run, but is only an annoying (but harmless) message in the console output. Is this also the case for you?
If it does affect your test's run can you elaborate? Can you show the test output, and the execution log, of your test also?

**Comment by reators** [comment]
On the Webbrowser the test hangs infinitely. Console output-button isn't shown/ presented, so there's no test output. But this happened with above test only one time. Every other call of the test succeeded successfully.
Then I tried to call the original (more lengthy) test script with scenarios and custom code and got above stacktrace again (with same hang and no test output).
I continued debugging and boiled it down to the use of my own custom fixture code written in Java. This code tries to access items in the DOM which don't exist (any more due to some changes in the Angular app I want to test).
By omitting the custom code (as a quick fix) all tests run successfully.
That doesn't explain the weird Exception (which looks unrelated to the source of the problem) but helps me to bridge the time until the custom fixture is fixed.

**Comment by fhoeben** [comment]
So to me it seems there are two issues:

- your custom fixture's code cannot handle a missing DOM element and makes a test hang
- FitNesse sometimes (first access of a `?suite' URL?) displays an annoying error in the console output, but that does not impact test execution.

I'm closing this issue as it does not seem to be related to this project's code. If you find the error in the console output annoying enough you could create an issue for it against https://github.com/unclebob/fitnesse
