### ISSUE TITLE
Nullpointer when setting null values as prefixes

### ISSUE THREAD

**Issue by koosg** [fhoeben/hsac-fitnesse-fixtures#36]
Since the set operation doesn't check if a null is supplied, but simply sets it, we actually have a key-value pair with key - null.
When we then try to override this key, we get a nullpointer exception, since a check exists to see if it is already a known value which isn't null-proof.
To test: add("key", null); add("key","something")
__EXCEPTION__:java.lang.NullPointerException
	at nl.hsac.fitnesse.fixture.util.NamespaceContextImpl.add(NamespaceContextImpl.java:30) [hsac-fitnesse-fixtures-2.4.1.jar]
	at nl.hsac.fitnesse.fixture.Environment.registerNamespace(Environment.java:356) [hsac-fitnesse-fixtures-2.4.1.jar]
	at nl.hsac.fitnesse.fixture.slim.XmlHttpTest.registerPrefixForNamespace(XmlHttpTest.java:26) [hsac-fitnesse-fixtures-2.4.1.jar]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:88) [rt.

**Comment by fhoeben** [comment]
you want to ensure no prefix remains in the context after a test, you can place the 'register("key", null)' call in a TearDown page, so it will be executed after a test that actually sets a (non-null) value.

But of course this is a bug and I will fix.
