### ISSUE TITLE
Bug: exception in ScriptLanguageFixture

### ISSUE THREAD

**Issue by teunisv** [fhoeben/hsac-fitnesse-fixtures#392]
HsacExamples.SlimTests.UtilityFixtures.ScriptLanguageFixture

`__EXCEPTION__:java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "e" is null
at nl.hsac.fitnesse.fixture.slim.ScriptLanguageFixture.lambda$putAllValues$0(ScriptLanguageFixture.java:164) [hsac-fitnesse-fixtures-4.30.0.jar]
at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723) [rt.jar]
at nl.hsac.fitnesse.fixture.slim.ScriptLanguageFixture.putAllValues(ScriptLanguageFixture.java:164) [hsac-fitnesse-fixtures-4.30.0.jar]
at nl.hsac.fitnesse.fixture.slim.ScriptLanguageFixture.evaluate(ScriptLanguageFixture.java:32) [hsac-fitnesse-fixtures-4.30.0.jar]
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [n/a]`

**Comment by fhoeben** [comment]
Any chance you are running on a Java version higher than 11? That is not supported, see also https://github.com/unclebob/fitnesse/issues/1338. (There is no JavaScript engine in these Java versions)
You probably could run on these JVMs, but you would have to explicitly configure a scripting engine for it...

**Comment by teunisv** [comment]
Yeah that pc runs Java 13, guess i will program another way to calculate numbers.

Closed: works find on older Java version

**Comment by tcnh** [comment]
For reference, as I encountered some questions regarding this now that more people move to Java 17 or 21:
If you run into this exception with script language fixture, make sure to add a dependency on openjdk's nashorn release to your project, and make sure it gets copied to the fixtures directory (if you use the hsac sample project's pom as a base this happens automatically).

Script language fixture will then discover the nashorn (js/ecma) scriptengine on the classpath and load that.

```xml
<dependency>
    <groupId>org.openjdk.nashorn</groupId>
    <artifactId>nashorn-core</artifactId>
    <version>15.4</version>
</dependency>
```
