### ISSUE TITLE
GitHub action workflow not working

### ISSUE THREAD

**Issue by fhoeben** [fhoeben/hsac-fitnesse-fixtures#404]
@tcnh the newly installed workflow does not work.

It seems to fail on the step to determine the current value, but doesn't detect this problem continues to release maven package and fails there stopping the workflow.

First error I see:
```
Run JActions/maven-version@v1.0.0
[8](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:8)
Run echo "::set-output name=resolved-version::$(mvn -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec --quiet)"
[9](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:9)
  echo "::set-output name=resolved-version::$(mvn -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec --quiet)"
[10](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:10)
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
[11](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:11)
  env:
[12](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:12)
    JAVA_HOME_8.0.322_x64: /opt/hostedtoolcache/jdk/8.0.322/x64
[13](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:13)
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.322/x64
[14](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:14)
    JAVA_HOME_8_0_322_X64: /opt/hostedtoolcache/jdk/8.0.322/x64
[15](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:15)
Error: Could not find or load main class 5.0
[16](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:5:16)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```

And then in release:
```
Run samuelmeuli/action-maven-publish@v1
[2](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:2)
  with:
[3](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:3)
    maven_profiles: release
[4](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:4)
    gpg_private_key: ***
[5](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:5)
    gpg_passphrase: ***
[6](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:6)
    nexus_username: ***
[7](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:7)
    nexus_password: ***
[8](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:8)
    server_id: ossrh
[9](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:9)
    maven_goals_phases: clean deploy
[10](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:10)
  env:
[11](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:11)
    JAVA_HOME_8.0.322_x64: /opt/hostedtoolcache/jdk/8.0.322/x64
[12](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:12)
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.322/x64
[13](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:13)
    JAVA_HOME_8_0_322_X64: /opt/hostedtoolcache/jdk/8.0.322/x64
[14](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:14)
Importing GPG key…
[15](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:15)
gpg: directory '/home/runner/.gnupg' created
[16](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:16)
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
[17](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:17)
gpg: no valid OpenPGP data found.
[18](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:18)
gpg: Total number processed: 0
[19](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:19)
child_process.js:674
[20](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:20)
    throw err;
[21](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:21)
    ^
[22](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:22)

[23](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:23)
Error: Command failed: gpg --import --batch /home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/private-key.txt
[24](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:24)
    at checkExecSyncError (child_process.js:635:11)
[25](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521203426?check_suite_focus=true#step:6:25)
    at execSync (child_process.js:671:15)
```

I believe the second error indicates I didn't put correct values in my secrets. I'll try to fix that.

Can you look at the first issue, and maybe find a way to stop the workflow on first action failure instead of it continuing?

**Comment by fhoeben** [comment]
I fixed the secrets issue, the release stage now gets further, but still fails:

```
[INFO] --- maven-gpg-plugin:1.6:sign (sign-artifacts) @ hsac-fitnesse-fixtures ---
[1898](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1898)
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar
[1899](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1899)
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar (38 kB at 1.3 MB/s)
[1900](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1900)
gpg: signing failed: Inappropriate ioctl for device
[1901](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1901)
gpg: signing failed: Inappropriate ioctl for device
[1902](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1902)
[INFO] ------------------------------------------------------------------------
[1903](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1903)
[INFO] BUILD FAILURE
[1904](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1904)
[INFO] ------------------------------------------------------------------------
[1905](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1905)
[INFO] Total time:  38.110 s
[1906](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1906)
[INFO] Finished at: 2022-03-12T10:10:13Z
[1907](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1907)
[INFO] ------------------------------------------------------------------------
[1908](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1908)
Error:  Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project hsac-fitnesse-fixtures: Exit code: 2 -> [Help 1]
[1909](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1909)
Error:  
[1910](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1910)
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
[1911](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1911)
Error:  Re-run Maven using the -X switch to enable full debug logging.
[1912](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1912)
Error:  
[1913](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1913)
Error:  For more information about the errors and possible solutions, please read the following articles:
[1914](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1914)
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[1915](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1915)
child_process.js:674
[1916](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1916)
    throw err;
[1917](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1917)
    ^
[1918](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1918)

[1919](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521261512?check_suite_focus=true#step:6:1919)
Error: Command failed: mvn clean deploy --batch-mode --activate-profiles release --settings /home/runner/work/_actions/samuelmeuli/action-maven-publish/v1/settings.xml
```

**Comment by fhoeben** [comment]
@tcnh a bit further along now, but I think this error might be a result of the earlier error:

```
Run actions/create-release@v1
[2](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:2)
  with:
[3](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:3)
  Error: ame: [ERROR] Command execution failed.
[4](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:4)
  Error: se_name: [ERROR] Command execution failed.
[5](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:5)
    draft: false
[6](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:6)
    prerelease: false
[7](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:7)
  env:
[8](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:8)
    JAVA_HOME_8.0.322_x64: /opt/hostedtoolcache/jdk/8.0.322/x64
[9](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:9)
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.322/x64
[10](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:10)
    JAVA_HOME_8_0_322_X64: /opt/hostedtoolcache/jdk/8.0.322/x64
[11](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:11)
    GITHUB_TOKEN: ***
[12](https://github.com/fhoeben/hsac-fitnesse-fixtures/runs/5521406965?check_suite_focus=true#step:8:12)
Error: Validation Failed: {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"}, {"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not well-formed"}, {"resource":"Release","code":"custom","message":"Published releases must have a valid tag"}
```

**Comment by fhoeben** [comment]
I believe the release to Maven central has worked. I'll create a release on GitHub manually now

**Comment by fhoeben** [comment]
@tcnh I replaced the `JActions/maven-version@v1.0.0` step by the commands I also used in the gitlab run this seems to work...

**Comment by tcnh** [comment]
Cool! So everything works now? Do I still need to check for the docker release or do you want to keep that at GitLab?

**Comment by fhoeben** [comment]
@tcnh I would like to have the docker release as part of the gitlab build (so I only push if docker containers actually work).
