### ISSUE TITLE
"Wait for visible" sometimes throws "org.openqa.selenium.JavascriptException: javascript error: Right-hand side of 'instanceof' is not an object"

### ISSUE THREAD

**Issue by DLeijenKeylane** [fhoeben/hsac-fitnesse-fixtures#423]
For out FitNesse runs, we suddenly see tests failing with the following (or at least very similar) stacktraces:
`org.openqa.selenium.JavascriptException: javascript error: Right-hand side of 'instanceof' is not an object
(Session info: chrome=103.0.5060.53)
Build info: version: '4.1.3', revision: '7b1ebf28ef'
System info: host: 'fitnesse', ip: '10.11.189.16', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.62.1.el7.x86_64', java.version: '11.0.8'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [fa6eb10ed66ce34bf06ce358a729fccf, findElements {using=xpath, value=.//text()[contains(normalize-space(translate(., ' ', ' ')),'Next')]/..}]
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 103.0.5060.53, chrome: {chromedriverVersion: 103.0.5060.53 (a1711811edd7..., userDataDir: /tmp/.com.google.Chrome.aZLMzW}, goog:chromeOptions: {debuggerAddress: localhost:40143}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), se:cdp: ws://localhost:40143/devtoo..., se:cdpVersion: 103.0.5060.53, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: ignore, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: fa6eb10ed66ce34bf06ce358a729fccf
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:200)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:133)
at org.openqa.selenium.remote.codec.w3c.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:53)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:184)
at org.openqa.selenium.remote.service.DriverCommandExecutor.invokeExecute(DriverCommandExecutor.java:167)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:142)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:567)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$2.findElements(ElementLocation.java:179)
at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:102)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:400)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:392)
at org.openqa.selenium.By$BaseW3CLocator.findElements(By.java:405)
at org.openqa.selenium.By$ByXPath.findElements(By.java:279)
at nl.hsac.fitnesse.fixture.util.selenium.by.LazyPatternBy.findElements(LazyPatternBy.java:33)
at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElements(ElementLocation.java:146)
at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:102)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:400)
at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:392)
at nl.hsac.fitnesse.fixture.util.selenium.by.BestMatchBy.findElement(BestMatchBy.java:49)
at nl.hsac.fitnesse.fixture.util.selenium.by.FirstElementBy.getWebElement(FirstElementBy.java:52)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findElement(SeleniumHelper.java:1180)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.lambda$findElement$2(SeleniumHelper.java:888)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.doInCurrentContext(SeleniumHelper.java:932)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findElement(SeleniumHelper.java:888)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.lambda$getElementToCheckVisibility$0(SeleniumHelper.java:209)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findByTechnicalSelectorOr(SeleniumHelper.java:232)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.getElementToCheckVisibility(SeleniumHelper.java:208)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.getElementToCheckVisibility(BrowserTest.java:2430)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.lambda$findByTechnicalSelectorOr$30(BrowserTest.java:2982)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.findByTechnicalSelectorOr(SeleniumHelper.java:232)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.findByTechnicalSelectorOr(BrowserTest.java:2982)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.lambda$getElementToCheckVisibility$25(BrowserTest.java:2434)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.doInContainer(BrowserTest.java:1338)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.getElementToCheckVisibility(BrowserTest.java:2434)
at com.keylane.fitnesse.web.KeylaneBrowserTest.getElementToCheckVisibility(KeylaneBrowserTest.java:427)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitForVisibleIn(BrowserTest.java:1508)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitForVisible(BrowserTest.java:1501)
at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322)
at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:65)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.superInvoke(BrowserTest.java:158)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.lambda$invokedWrappedInWaitUntil$0(BrowserTest.java:124)
at nl.hsac.fitnesse.fixture.util.selenium.TryAllFramesConditionDecorator.lambda$apply$1(TryAllFramesConditionDecorator.java:27)
at nl.hsac.fitnesse.fixture.util.selenium.AllFramesDecorator.invokeInFrames(AllFramesDecorator.java:64)
at nl.hsac.fitnesse.fixture.util.selenium.AllFramesDecorator.apply(AllFramesDecorator.java:49)
at nl.hsac.fitnesse.fixture.util.selenium.TryAllFramesConditionDecorator.apply(TryAllFramesConditionDecorator.java:27)
at nl.hsac.fitnesse.fixture.util.selenium.TryAllFramesConditionDecorator.apply(TryAllFramesConditionDecorator.java:11)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.lambda$getConditionIgnoringStaleElement$4(SeleniumHelper.java:1123)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
at nl.hsac.fitnesse.fixture.util.selenium.SeleniumHelper.waitUntil(SeleniumHelper.java:1109)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitUntilImpl(BrowserTest.java:2759)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.waitUntilOrStop(BrowserTest.java:2705)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.invokedWrappedInWaitUntil(BrowserTest.java:141)
at nl.hsac.fitnesse.fixture.slim.web.BrowserTest.invoke(BrowserTest.java:107)
at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:45)
at jdk.internal.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322)
at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:305)
at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:290)
at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:217)
at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18)
at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18)
at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139)
at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112)
at fitnesse.slim.instructions.CallAndOptionalAssignInstruction.executeInternal(CallAndOptionalAssignInstruction.java:30)
at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29)
at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49)
at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43)
at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85)
at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:82)
at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:75)
at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:62)
at fitnesse.slim.SlimServer.serve(SlimServer.java:47)
at fitnesse.testsystems.slim.InProcessSlimClient$1.run(InProcessSlimClient.java:55)
at java.base/java.lang.Thread.run(Thread.java:834)`

Looking at the screenshot, the element we're waiting on is visible on the screen at the time of the error.

Recent changes to our pipeline:
- Upgraded Chrome from 73.0.3683.68 to 103.0.5060.53
- Upgraded Tomcat from 8.5.54 to 9.0.62
- Upgraded from version 4.30.0 to 5.2.11 of this project
- Upgraded hsac-fitnesse-plugin from 1.31.0 to 1.32.9

**Comment by fhoeben** [comment]
Any chance you can provide a reproduction path? At the moment I don't seesaw I could help you.

**Comment by DLeijenKeylane** [comment]
An upgrade to a newer version seems to have resolved it. Unclear what caused it, and unclear why this is now resolved.
