### ISSUE TITLE
Using FixtureDebugTest, is it possible to debug an url with responder and inputs ?

### ISSUE THREAD

**Issue by pvbemmelen62** [fhoeben/hsac-fitnesse-fixtures#427]
I have implemented a fixture with a command that generates Fitnesse scripts, from specs in an Excel file.
I have also added behaviour, that prior to generating Fitnesse scripts, any old scripts generated earlier, are deleted first.
But I also want to add behaviour, to first delete any old test results.

I thought it a good idea, to use java code that is used by the implementation of the responder "purgeHistory" .
I want to reuse such java code in my fixture.
I saw from the source code, that fitnesse.reporting.history.HistoryPurger  is probably involved, but I have trouble to see how "MyWikiPage" is taken into account by that code.

So I thought to use FixtureDebugTest to debug/step through the code:

```
package nl.praegus;

import fitnesse.junit.FitNesseRunner;
import nl.praegus.fitnesse.junit.runner.ToolchainTestRunner;
import org.junit.runner.RunWith;

/**
 * Test class to allow fixture code to be debugged, or run by build server.
 */

@RunWith(ToolchainTestRunner.class)
@FitNesseRunner.Suite("MyWikiPage?responder=purgeHistory&days=0")
public class FixtureDebugTest {
}
```
However, when in IntelliJ  I do Run > Debug > FixtureDebugTest
I get the error:

```
java.lang.IllegalArgumentException: No page MyWikiPage?responder=purgeHistory&days=0
	at fitnesse.junit.FitNesseRunner.initChildren(FitNesseRunner.java:522)
	at fitnesse.junit.FitNesseRunner.getTestRun(FitNesseRunner.java:461)
	at fitnesse.junit.FitNesseRunner.getChildren(FitNesseRunner.java:470)
	at org.junit.runners.ParentRunner.getFilteredChildren(ParentRunner.java:534)
	at org.junit.runners.ParentRunner.getDescription(ParentRunner.java:400)
	at org.junit.runners.model.RunnerBuilder.configureRunner(RunnerBuilder.java:81)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:72)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:50)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
```
Is it possible to debug an url with responder and inputs ?

**Comment by fhoeben** [comment]
@pvbemmelen62 the FixtureDebugTest just executes the suite or test. It doesn't start the actual wiki server so responders cannot be debugged that way. (You could debug those by just starting FitNesse's main class in a debugger and the invoke the URL you are looking for, I think)

Did you see the acceptance tests have a test that generates a suite? It's not the same as what your planning, but I thought I would highlight it as it allows the input to be maintained in a text file (a .wiki file) instead of an Excel which is nicer if you want to keep the input in version management (and copy/n/paste between the Excel and the wiki editor has, of course, been a feature for years). Other than that the approach taken there might (or might not) provide some input/ideas to how you could work based on Excel.

I haven't looked at `fitnesse.reporting.history.HistoryPurger` before, so I can't help you with that. (I've never been very specific with test history: I rely on the CI server's reports, locally I just delete all test results once every so often.)
