### ISSUE TITLE
Unable to launch a browser (chrome or Firefox) 

### ISSUE THREAD

**Issue by Sujays08** [fhoeben/hsac-fitnesse-fixtures#519]
Hi,

Currently I am unable to launch browser as its giving the error below. Any help would be greatly appreciated. I tried with different permutations of impacting factors given below but with no luck.

__EXCEPTION__:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure. 

hsac Fitnesse Fixture Version: latest 5.2.40
Fitnesse: v20221219
Java Version: 1.8.0_361
Chrome version: any version after March 2023
Firefox: ANy version after March 2023
Fitness is ran from local machine 

**Test extract:**
|Import                           |
|nl.hsac.fitnesse.fixture.slim.web|
|nl.hsac.fitnesse.fixture.slim    |

|script          |selenium driver setup                                                                                                                  |
|start driver for     |firefox                                                                                                          |

__EXCEPTION__:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.  Host info: host: 'XXX-001.local', ip: 'XXXXXXXXXXX' at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.DriverManager.getSeleniumHelper(DriverManager.java:52) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.setAndUseDriverFactory(SeleniumDriverSetup.java:288) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverForWithProfile(SeleniumDriverSetup.java:100) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverFor(SeleniumDriverSetup.java:105) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20221219] at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:65) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:45) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:305) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:290) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:217) [fitnesse-standalone.jar:20221219] at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20221219] at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20221219] at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20221219] at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20221219] at fitnesse.slim.instructions.CallAndOptionalAssignInstruction.executeInternal(CallAndOptionalAssignInstruction.java:30) [fitnesse-standalone.jar:20221219] at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:84) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:77) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:64) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.serve(SlimServer.java:49) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20221219] Caused by: org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.  Host info: host: 'DAC-0114.local', ip: 'fe80:0:0:0:20:41bd:be7f:56c%en0' at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:549) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:151) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:146) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:130) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:110) [selenium-firefox-driver-4.10.0.jar] at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.LocalDriverFactory.createDriver(LocalDriverFactory.java:50) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.DriverManager.getSeleniumHelper(DriverManager.java:46) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.setAndUseDriverFactory(SeleniumDriverSetup.java:288) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverForWithProfile(SeleniumDriverSetup.java:100) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverFor(SeleniumDriverSetup.java:105) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20221219] at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:65) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:45) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:305) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:290) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:217) [fitnesse-standalone.jar:20221219] at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20221219] at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20221219] at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20221219] at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20221219] at fitnesse.slim.instructions.CallAndOptionalAssignInstruction.executeInternal(CallAndOptionalAssignInstruction.java:30) [fitnesse-standalone.jar:20221219] at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:84) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:77) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:64) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.serve(SlimServer.java:49) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20221219] Caused by: org.openqa.selenium.WebDriverException: Timed out waiting for driver process to start. Build info: version: '4.10.0', revision: 'c14d967899' System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2.1', java.version: '1.8.0_361' Driver info: driver.version: FirefoxDriver at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:215) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:119) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:531) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:227) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:154) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:151) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:146) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:130) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:125) [selenium-firefox-driver-4.10.0.jar] at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:110) [selenium-firefox-driver-4.10.0.jar] at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.LocalDriverFactory.createDriver(LocalDriverFactory.java:50) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.DriverManager.getSeleniumHelper(DriverManager.java:46) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.setAndUseDriverFactory(SeleniumDriverSetup.java:288) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverForWithProfile(SeleniumDriverSetup.java:100) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverFor(SeleniumDriverSetup.java:105) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20221219] at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:65) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:45) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:305) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:290) [fitnesse-standalone.jar:20221219] at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:217) [fitnesse-standalone.jar:20221219] at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20221219] at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20221219] at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20221219] at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20221219] at fitnesse.slim.instructions.CallAndOptionalAssignInstruction.executeInternal(CallAndOptionalAssignInstruction.java:30) [fitnesse-standalone.jar:20221219] at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20221219] at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:84) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:77) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:64) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimServer.serve(SlimServer.java:49) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20221219] at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20221219]

**Comment by fhoeben** [comment]
You're on Intel based Mac, correct?

I just tried locally on my M1 based Mac and both Chrome and Firefox started without problems.
In my environment I was on FitNesse 20230503.

Do you run into the issue when you:
* do a fresh checkout (or download it in zip format) of 
https://github.com/fhoeben/sample-fitnesse-project
* from that directory run `mvn clean compile dependency:copy-dependencies exec:exec`
* Try to run http://localhost:9090/HsacExamples.SlimTests.BrowserTests.ScriptTest?test

**Comment by Sujays08** [comment]
Firstly thank you very much for such a quick response.

I am currently using a Macbook Pro with Apple M2.When I try to do a clean compile, I saw the logs and noticed that downloaded webdrivers are getting installed as mac-M1. However error remains the same. 

Here are the steps I followed:
**Scenario 1:**
1) Downloaded the Fitnesse standalone jar (version 20230503) and placed in folder X
2) Dowloaded the hsac-fitnesse-fixtures-master zip and extracted the same into folder X
3) Dowloaded the Chromedriver and placed in folder X
4) Ran the testcase, it resulted in the error 
EXCEPTION:ABORT_SLIM_TEST:nl.hsac.fitnesse.fixture.slim.StopTestException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

**Scenario 2**
After Step 2 from above, if I don't place the driver explicitly and run the test, I am getting following error. 

Note: Before March 2023, if I did this, it used to fail with a message saying webdriver is not present with name. Upon placing it used to work. When the browsers got upgraded to Chrome 110.xx and above and Firefox 109.X and above, it stopped working.


__EXCEPTION__:org.openqa.selenium.remote.NoSuchDriverException: chromedriver located at chromedriver-mac-%dbit, but invalid For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/ Build info: version: '4.10.0', revision: 'c14d967899' System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '13.2.1', java.version: '1.8.0_361' Driver info: driver.version: ChromeDriver at org.openqa.selenium.remote.service.DriverFinder.getPath(DriverFinder.java:45) [selenium-remote-driver-4.10.0.jar] at org.openqa.selenium.chrome.ChromeDriver.generateExecutor(ChromeDriver.java:98) [selenium-chrome-driver-4.10.0.jar] at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:87) [selenium-chrome-driver-4.10.0.jar] at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:82) [selenium-chrome-driver-4.10.0.jar] at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:71) [selenium-chrome-driver-4.10.0.jar] at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.LocalDriverFactory.createDriver(LocalDriverFactory.java:54) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.util.selenium.driverfactory.DriverManager.getSeleniumHelper(DriverManager.java:46) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.setAndUseDriverFactory(SeleniumDriverSetup.java:288) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverForWithProfile(SeleniumDriverSetup.java:100) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.web.SeleniumDriverSetup.startDriverFor(SeleniumDriverSetup.java:105) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20230503] at nl.hsac.fitnesse.fixture.slim.SlimFixture.invoke(SlimFixture.java:65) [hsac-fitnesse-fixtures.jar] at nl.hsac.fitnesse.fixture.slim.SlimFixture.aroundSlimInvoke(SlimFixture.java:45) [hsac-fitnesse-fixtures.jar] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_361] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_361] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_361] at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_361] at fitnesse.slim.fixtureInteraction.SimpleInteraction.methodInvoke(SimpleInteraction.java:322) [fitnesse-standalone.jar:20230503] at fitnesse.slim.fixtureInteraction.SimpleInteraction.callMethod(SimpleInteraction.java:305) [fitnesse-standalone.jar:20230503] at fitnesse.slim.fixtureInteraction.SimpleInteraction.invokeMethod(SimpleInteraction.java:290) [fitnesse-standalone.jar:20230503] at fitnesse.slim.fixtureInteraction.SimpleInteraction.findAndInvoke(SimpleInteraction.java:217) [fitnesse-standalone.jar:20230503] at fitnesse.slim.MethodExecutor.findAndInvoke(MethodExecutor.java:18) [fitnesse-standalone.jar:20230503] at fitnesse.slim.FixtureMethodExecutor.execute(FixtureMethodExecutor.java:18) [fitnesse-standalone.jar:20230503] at fitnesse.slim.StatementExecutor.getMethodExecutionResult(StatementExecutor.java:139) [fitnesse-standalone.jar:20230503] at fitnesse.slim.StatementExecutor.call(StatementExecutor.java:112) [fitnesse-standalone.jar:20230503] at fitnesse.slim.instructions.CallAndOptionalAssignInstruction.executeInternal(CallAndOptionalAssignInstruction.java:30) [fitnesse-standalone.jar:20230503] at fitnesse.slim.instructions.Instruction.execute(Instruction.java:29) [fitnesse-standalone.jar:20230503] at fitnesse.slim.ListExecutor$Executive.executeStatement(ListExecutor.java:49) [fitnesse-standalone.jar:20230503] at fitnesse.slim.ListExecutor$Executive.executeStatements(ListExecutor.java:43) [fitnesse-standalone.jar:20230503] at fitnesse.slim.ListExecutor.execute(ListExecutor.java:85) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimServer.executeInstructions(SlimServer.java:84) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimServer.processOneSetOfInstructions(SlimServer.java:77) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimServer.tryProcessInstructions(SlimServer.java:64) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimServer.serve(SlimServer.java:49) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimService.handle(SlimService.java:169) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimService.acceptOne(SlimService.java:177) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimService.accept(SlimService.java:139) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimService.startWithFactory(SlimService.java:92) [fitnesse-standalone.jar:20230503] at fitnesse.slim.SlimService.main(SlimService.java:57) [fitnesse-standalone.jar:20230503]

**Comment by Sujays08** [comment]
Hi, sorry to bother you. Would kindly let me know if you had a chance to check my comments?

**Comment by fhoeben** [comment]
I had a quick look, but I cannot immediately see what is going wrong. 

Did you also try the approach I suggested, using the sample project? This should automatically place the standalone and download the correct web driver (to the correct location).

Or could you describe what happens when you: first ensure no (FitNesse) process is listening on port 9090 (i.e. opening http://localhost:9090 in a browser should not show a webpage), download and unzip https://github.com/fhoeben/hsac-fitnesse-fixtures/releases/download/5.2.40/hsac-fitnesse-fixtures-5.2.40-standalone.zip in new directory, open a terminal window in that directory and start using `java -jar fitnesse-standalone.jar  -p 9090` (ensure `java` in this terminal is a Java 8 JVM) and then open http://localhost:9090/HsacExamples.SlimTests.BrowserTests.ScriptTest?test

In your own description you don't say how you actually start FitNesse or what test you are running
