### ISSUE TITLE
hsac fitnesse fixtures not working after angular upgrade to 14 in headless chrome

### ISSUE THREAD

**Issue by rathodrajnesh** [fhoeben/hsac-fitnesse-fixtures#580]
Fitnesse testcases were running before upgrade to angular 14, but after upgrading it not working. 

Script to start it

```
import org.apache.tools.ant.taskdefs.condition.Os

apply plugin: 'java'
apply plugin: 'de.undercouch.download'

ext {
    fitnesse_port = '9090'
    fitnesse_wiki_dir = 'wiki'
    fitnesse_fixture_dir = 'fixtures'
    fitnesse_version = '20230503'
    hsac_fixtures_version = '5.2.39'
    hsac_pdf_fixtures_version = '0.0.5'
    chromedriver_version = '114.0.5735.90'
}

// Set specific selenium.version for the mavenBom of spring-boot-dependencies
ext['selenium.version'] = '4.9.1'

clean {
    delete = ['target', 'build',
              "${fitnesse_wiki_dir}/${fitnesse_fixture_dir}",
              "${fitnesse_wiki_dir}/FitNesseRoot/files/screenshots",
              "${fitnesse_wiki_dir}/FitNesseRoot/files/pagesources",
              "${fitnesse_wiki_dir}/FitNesseRoot/files/downloads",
              "${fitnesse_wiki_dir}/FitNesseRoot/files/galen-reports"]
}

tasks.register("deleteHsacContent", Delete) {
    delete fileTree(fitnesse_wiki_dir) {
        include 'fitnesse-standalone.jar'
        include 'plugins/hsac-*'
        include 'webdrivers'
        include 'FitNesseRoot/Hsac*.wiki'
        include 'FitNesseRoot/HsacAcceptanceTests'
        include 'FitNesseRoot/HsacExamples'
    }
}

configurations {
    fixtures
    fixtures_standalone
}

dependencies {
    implementation("org.fitnesse:fitnesse:${fitnesse_version}")
    fixtures "nl.hsac:hsac-fitnesse-fixtures:${hsac_fixtures_version}"
    fixtures "nl.hsac:hsac-fitnesse-pdf:${hsac_pdf_fixtures_version}"
    fixtures_standalone "nl.hsac:hsac-fitnesse-fixtures:${hsac_fixtures_version}:standalone@zip"

    implementation configurations.fixtures

    testImplementation('junit:junit')
}

sourceSets {
    main {
        output.resourcesDir = file("${fitnesse_wiki_dir}/${fitnesse_fixture_dir}")
        java.outputDir = file("${fitnesse_wiki_dir}/${fitnesse_fixture_dir}")
    }
}

tasks.register("copyFixturesToStandalone", Copy) {
    from configurations.fixtures
    into file("${fitnesse_wiki_dir}/${fitnesse_fixture_dir}")
}

tasks.register("downloadChromedriverForLinux", Download) {
    doFirst {
        file("${buildDir}/webdrivers").mkdirs()
    }

    src "https://chromedriver.storage.googleapis.com/${chromedriver_version}/chromedriver_linux64.zip"
    dest "${buildDir}/webdrivers"
    overwrite true

    doLast {
        copy {
            from { // use of closure defers evaluation until execution time
                zipTree(file("${buildDir}/webdrivers/chromedriver_linux64.zip"))
            }
            into file("${fitnesse_wiki_dir}/webdrivers")
            rename {
                "${it}-linux-64bit"
            }
        }
    }
}

tasks.register("downloadChromedriverForMac", Download) {
    doFirst {
        file("${buildDir}/webdrivers").mkdirs()
    }

    src "https://chromedriver.storage.googleapis.com/${chromedriver_version}/chromedriver_mac64.zip"
    dest "${buildDir}/webdrivers"
    overwrite true

    doLast {
        copy {
            from { // use of closure defers evaluation until execution time
                zipTree(file("${buildDir}/webdrivers/chromedriver_mac64.zip"))
            }
            into file("${fitnesse_wiki_dir}/webdrivers")
            rename {
                "${it}-mac-64bit"
            }
        }
    }
}

tasks.register("downloadWebdriversForWindows", Copy) {
    dependsOn configurations.fixtures_standalone

    from { // use of closure defers evaluation until execution time
        configurations.fixtures_standalone.collect { zipTree(it) }
    }
    into file(fitnesse_wiki_dir)

    include 'webdrivers/*-windows-*'
}

tasks.register("expandStandalone", Copy) {
    dependsOn configurations.fixtures_standalone

    from { // use of closure defers evaluation until execution time
        configurations.fixtures_standalone.collect { zipTree(it) }
    }
    into file(fitnesse_wiki_dir)

    exclude 'plugins.properties'
    exclude "${fitnesse_fixture_dir}/**"
    exclude 'plugins/maven-*'
    exclude 'webdrivers/**'
    if (Os.isFamily('mac')) {
        dependsOn downloadChromedriverForMac
    } else if (Os.isFamily('windows')) {
        dependsOn downloadWebdriversForWindows
    } else if (Os.isName('linux')) {
        dependsOn downloadChromedriverForLinux
    }

    eachFile { FileCopyDetails fcd ->
        excludeIfMissingOrOlder(fcd, "${project.projectDir}/${fitnesse_wiki_dir}")
    }
}

tasks.register("startWiki", Exec) {
    dependsOn 'expandStandalone', 'copyFixturesToStandalone'

    group = LifecycleBasePlugin.VERIFICATION_GROUP
    description = 'Start local FitNesse wiki server to run tests one by one'

    workingDir fitnesse_wiki_dir
    commandLine 'java', '-jar', 'fitnesse-standalone.jar', '-p', fitnesse_port
}

test {
    exclude 'nl/nobilex/fitnesse/FixtureDebugTest.class'
}

tasks.register("extractPluginsOnly", Copy) {
    dependsOn configurations.fixtures_standalone

    from { // use of closure defers evaluation until execution time
        configurations.fixtures_standalone.collect { zipTree(it) }
    }
    into file(fitnesse_wiki_dir)

    include 'plugins/**'

    eachFile { FileCopyDetails fcd ->
        excludeIfMissingOrOlder(fcd, "${project.projectDir}/wiki")
    }
}

static def excludeIfMissingOrOlder(FileCopyDetails fcd, String targetPath) {
    def target = new File(targetPath, fcd.path)
    if (target.exists()) {
        if (target.lastModified() >= fcd.lastModified) {
            fcd.exclude()
        }
    }
}
```

pipeline logs

```Nobilex started
Starting test run
For all containers, start docker-tail to a file on disk in the /builds/nobilex/nobilex/fitnesse/target directory
Starting docker-tail for nobilex_loadbalancer_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_loadbalancer_1.docker.log
Starting docker-tail for nobilex_testconsole-web_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_testconsole-web_1.docker.log
Starting docker-tail for nobilex_api-gateway_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_api-gateway_1.docker.log
Starting docker-tail for nobilex_test-backend_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_test-backend_1.docker.log
Starting docker-tail for nobilex_search-indexer_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_search-indexer_1.docker.log
Starting docker-tail for nobilex_notarisbox-api-gateway_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_notarisbox-api-gateway_1.docker.log
Starting docker-tail for nobilex_api-external-gateway_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_api-external-gateway_1.docker.log
Starting docker-tail for nobilex_dossiers_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_dossiers_1.docker.log
Starting docker-tail for nobilex_search_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_search_1.docker.log
Starting docker-tail for nobilex_scheduler_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_scheduler_1.docker.log
Starting docker-tail for nobilex_documenten_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_documenten_1.docker.log
Starting docker-tail for nobilex_service-gateway_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_service-gateway_1.docker.log
Starting docker-tail for nobilex_ovb_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_ovb_1.docker.log
Starting docker-tail for nobilex_notarisbox_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_notarisbox_1.docker.log
Starting docker-tail for nobilex_objecten_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_objecten_1.docker.log
Starting docker-tail for nobilex_doc-generation_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_doc-generation_1.docker.log
Starting docker-tail for nobilex_relatiekaart_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_relatiekaart_1.docker.log
Starting docker-tail for nobilex_kantoor_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_kantoor_1.docker.log
Starting docker-tail for nobilex_notification_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_notification_1.docker.log
Starting docker-tail for nobilex_taken_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_taken_1.docker.log
Starting docker-tail for nobilex_afas_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_afas_1.docker.log
Starting docker-tail for nobilex_gebruiker_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_gebruiker_1.docker.log
Starting docker-tail for nobilex_facturen_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_facturen_1.docker.log
Starting docker-tail for nobilex_notarisboxportal_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_notarisboxportal_1.docker.log
Starting docker-tail for nobilex_word-add-in_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_word-add-in_1.docker.log
Starting docker-tail for nobilex_kantoorbeheer-web_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_kantoorbeheer-web_1.docker.log
Starting docker-tail for nobilex_notarisportaal_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_notarisportaal_1.docker.log
Starting docker-tail for nobilex_toxiproxy_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_toxiproxy_1.docker.log
Starting docker-tail for nobilex_outlook-add-in_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_outlook-add-in_1.docker.log
Starting docker-tail for nobilex_requestdemoportal_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_requestdemoportal_1.docker.log
Starting docker-tail for nobilex_sepa_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_sepa_1.docker.log
Starting docker-tail for nobilex_kik-xslt_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_kik-xslt_1.docker.log
Starting docker-tail for nobilex_nbx-platform-server_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_nbx-platform-server_1.docker.log
Starting docker-tail for nobilex_keycloak_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_keycloak_1.docker.log
Starting docker-tail for nobilex_postgres_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_postgres_1.docker.log
Starting docker-tail for nobilex_mongodb_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_mongodb_1.docker.log
Starting docker-tail for nobilex_elasticsearch_1 to /builds/nobilex/nobilex/fitnesse/target/nobilex_elasticsearch_1.docker.log
Starting parallel tests in Docker
Executing sequential tests first
Cleaning previous state for sequential
No stopped containers
Creating sequential
[1A[2K
Creating nobilex_loadbalancer_1           ... [32mdone[0m
[1BPulling fitnesse-sequential (hsac/fitnesse-fixtures-test-jre8-chrome-with-pdf:4.15.2-iron)...
4.15.2-iron: Pulling from hsac/fitnesse-fixtures-test-jre8-chrome-with-pdf
Digest: sha256:ccd6528f8176b75377fd9c77b64b1b60d357a54d6875a937ed94232219ca540d
Status: Downloaded newer image for hsac/fitnesse-fixtures-test-jre8-chrome-with-pdf:4.15.2-iron
Creating nobilex_fitnesse-sequential_1 ... 
Copying tests
Running tests for suite sequential
[1A[2K
Creating nobilex_fitnesse-sequential_1 ... [32mdone[0m
[1BStarting nobilex_fitnesse-sequential_1 ... 
Waiting for the Grid
Waiting for the Grid
[1A[2K
Starting nobilex_fitnesse-sequential_1 ... [32mdone[0m
[1BSelenium Grid is up - executing tests
java -cp wiki/fixtures:wiki/fixtures/* -DseleniumBrowser=chrome -DseleniumGridUrl=http://localhost:4444/wd/hub -Xmx192m -Xms192m -DreRunSuiteLocation=/fitnesse/target/sequential -DfitnesseSuiteToRun=Nobilex -DTENANT=fitnesse-sequential -DsuiteFilter=Sequential nl.hsac.fitnesse.junit.JUnitConsoleRunner nl.hsac.fitnesse.HsacFitNesseSuiteStarter
Nov 29, 2023 7:32:26 AM fitnesse.ConfigurationParameter loadProperties
INFO: No configuration file found (/fitnesse/wiki/plugins.properties)
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.MonthsFromToday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.YearsFromToday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.WeekDaysFromToday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DayOfWeek$Monday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DayOfWeek$Tuesday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DayOfWeek$Wednesday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DayOfWeek$Thursday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DayOfWeek$Friday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DayOfWeek$Saturday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DayOfWeek$Sunday
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.LastDayOfMonth
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomInt
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomString
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomBsn
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomEmail
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomIban
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomPostalCode
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomDutchLicensePlate
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DefineDefault
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DefineFromProperties
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.DefineDefaultFromProperties
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added symbol class nl.hsac.fitnesse.symbols.RandomUuid
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added Slim table type: table template: nl.hsac.fitnesse.slim.AutoArgScenarioTable
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory add
INFO: Added Slim table type: storyboard: nl.hsac.fitnesse.slim.StoryboardTable
Nov 29, 2023 7:32:26 AM nl.hsac.fitnesse.HsacPluginFeatureFactory registerSlimCoverageIfPossible
INFO: Registered test system slimcoverage
2023-11-29 07:32:28.101 testRun Started ('16' tests)
slim:in-process

2023-11-29 07:32:28.137 testSuite Started 'nl.hsac.fitnesse.HsacFitNesseSuiteStarter'
2023-11-29 07:32:28.137 test Started 'Nobilex.SuiteSetUp' (1 / 16)
2023-11-29 07:33:06.734 test Finished 'Nobilex.SuiteSetUp'

2023-11-29 07:33:06.734 test Started 'Nobilex.BackEndTests.Scheduler.Scheduler' (2 / 16)
2023-11-29 07:33:15.592 test Finished 'Nobilex.BackEndTests.Scheduler.Scheduler'

2023-11-29 07:33:15.592 test Started 'Nobilex.FrontEndTests.SuiteSetUp' (3 / 16)
Nov 29, 2023 7:33:25 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
2023-11-29 07:33:25.838 test Finished 'Nobilex.FrontEndTests.SuiteSetUp'

2023-11-29 07:33:25.838 test Started 'Nobilex.FrontEndTests.Algemeen.InactieveGebruikers.InactieveGebruikers' (4 / 16)
2023-11-29 07:33:42.085 test Failed 'Nobilex.FrontEndTests.Algemeen.InactieveGebruikers.InactieveGebruikers' message='failed' details='java.lang.AssertionError: <div><div>Timed-out waiting (after 15s).</div><div><a href="files/pagesources/org.openqa.selenium.TimeoutException.html" target="_blank">Page content</a>:<a href="files/screenshots/timeouts/BrowserTest/timeout.png" target="_blank"><img src="files/screenshots/timeouts/BrowserTest/timeout.png" title="/fitnesse/target/fitnesse-results/files/screenshots/timeouts/BrowserTest/timeout.png" height="200"/></a></div></div>
	at fitnesse.junit.JUnitRunNotifierResultsListener.firstFailure(JUnitRunNotifierResultsListener.java:168)
	at fitnesse.junit.JUnitRunNotifierResultsListener.testExceptionOccurred(JUnitRunNotifierResultsListener.java:90)
	at fitnesse.testsystems.CompositeTestSystemListener.testExceptionOccurred(CompositeTestSystemListener.java:61)
	at fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testExceptionOccurred(MultipleTestsRunner.java:225)
	at fitnesse.testsystems.CompositeTestSystemListener.testExceptionOccurred(CompositeTestSystemListener.java:61)
	at fitnesse.testsystems.slim.SlimTestSystem.testExceptionOccurred(SlimTestSystem.java:201)
	at fitnesse.testsystems.slim.SlimTestSystem.evaluateTables(SlimTestSystem.java:151)
	at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:131)
	at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:56)
	at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:93)
	at fitnesse.testrunner.run.PerTestSystemTestRun.executeTestSystemPages(PerTestSystemTestRun.java:64)
	at fitnesse.testrunner.run.PerTestSystemTestRun.startTestSystemAndExecutePages(PerTestSystemTestRun.java:47)
	at fitnesse.testrunner.run.PerTestSystemTestRun.executeTestPages(PerTestSystemTestRun.java:30)
	at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:67)
	at fitnesse.junit.FitNesseRunner.executeTests(FitNesseRunner.java:580)
	at fitnesse.junit.FitNesseRunner.runPages(FitNesseRunner.java:497)
	at nl.hsac.fitnesse.junit.HsacFitNesseRunner.runPages(HsacFitNesseRunner.java:216)
	at fitnesse.junit.FitNesseRunner.run(FitNesseRunner.java:478)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at nl.hsac.fitnesse.junit.JUnitConsoleRunner.runTests(JUnitConsoleRunner.java:37)
	at nl.hsac.fitnesse.junit.JUnitConsoleRunner.main(JUnitConsoleRunner.java:45)
'
2023-11-29 07:33:42.085 test Finished 'Nobilex.FrontEndTests.Algemeen.InactieveGebruikers.InactieveGebruikers'

2023-11-29 07:33:42.086 test Finished 'Nobilex.FrontEndTests.Algemeen.InactieveGebruikers.InactieveGebruikers'

2023-11-29 07:33:42.088 test Started 'Nobilex.FrontEndTests.Dashboard.Akten.OndertekenenMeerdereAktenRetry' (5 / 16)
2023-11-29 07:33:58.190 test Failed 'Nobilex.FrontEndTests.Dashboard.Akten.OndertekenenMeerdereAktenRetry' message='failed' details='java.lang.AssertionError: <div><div>Timed-out waiting (after 15s).</div><div><a href="files/pagesources/org.openqa.selenium.TimeoutException_1.html" target="_blank">Page content</a>:<a href="files/screenshots/timeouts/BrowserTest/timeout_1.png" target="_blank"><img src="files/screenshots/timeouts/BrowserTest/timeout_1.png" title="/fitnesse/target/fitnesse-results/files/screenshots/timeouts/BrowserTest/timeout_1.png" height="200"/></a></div></div>
	at fitnesse.junit.JUnitRunNotifierResultsListener.firstFailure(JUnitRunNotifierResultsListener.java:168)
	at fitnesse.junit.JUnitRunNotifierResultsListener.testExceptionOccurred(JUnitRunNotifierResultsListener.java:90)
	at fitnesse.testsystems.CompositeTestSystemListener.testExceptionOccurred(CompositeTestSystemListener.java:61)
	at fitnesse.testrunner.MultipleTestsRunner$InternalTestSystemListener.testExceptionOccurred(MultipleTestsRunner.java:225)
	at fitnesse.testsystems.CompositeTestSystemListener.testExceptionOccurred(CompositeTestSystemListener.java:61)
	at fitnesse.testsystems.slim.SlimTestSystem.testExceptionOccurred(SlimTestSystem.java:201)
	at fitnesse.testsystems.slim.SlimTestSystem.evaluateTables(SlimTestSystem.java:151)
	at fitnesse.testsystems.slim.SlimTestSystem.processTable(SlimTestSystem.java:131)
	at fitnesse.testsystems.slim.HtmlSlimTestSystem.processAllTablesOnPage(HtmlSlimTestSystem.java:56)
	at fitnesse.testsystems.slim.SlimTestSystem.runTests(SlimTestSystem.java:93)
	at fitnesse.testrunner.run.PerTestSystemTestRun.executeTestSystemPages(PerTestSystemTestRun.java:64)
	at fitnesse.testrunner.run.PerTestSystemTestRun.startTestSystemAndExecutePages(PerTestSystemTestRun.java:47)
	at fitnesse.testrunner.run.PerTestSystemTestRun.executeTestPages(PerTestSystemTestRun.java:30)
	at fitnesse.testrunner.MultipleTestsRunner.executeTestPages(MultipleTestsRunner.java:67)
	at fitnesse.junit.FitNesseRunner.executeTests(FitNesseRunner.java:580)
	at fitnesse.junit.FitNesseRunner.runPages(FitNesseRunner.java:497)
	at nl.hsac.fitnesse.junit.HsacFitNesseRunner.runPages(HsacFitNesseRunner.java:216)
	at fitnesse.junit.FitNesseRunner.run(FitNesseRunner.java:478)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:105)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:94)
	at nl.hsac.fitnesse.junit.JUnitConsoleRunner.runTests(JUnitConsoleRunner.java:37)
	at nl.hsac.fitnesse.junit.JUnitConsoleRunner.main(JUnitConsoleRunner.java:45)
'
2023-11-29 07:33:58.191 test Finished 'Nobilex.FrontEndTests.Dashboard.Akten.OndertekenenMeerdereAktenRetry'```


Using Ubuntu system and build is working good with docker container.

**Comment by fhoeben** [comment]
I'm sorry to say based on this information I really cannot help you.

You state the problem started to occur after an Angular upgrade so the problem probably occurs due to some JavaScript/HTML on the page. The error is a very generic timeout so you'll have to do some more digging to create an example that is reproducible to me before I can help you. And then the test startup scripts are probably not the most revevant, but the content of the page being tested and the test's wiki content.

What I can tell from the stack traces is that you are on a quite old version of the docker image. That does not have to be an issue, but _might_ be relevant.
