### ISSUE TITLE
cannot use git-plugin with latest version of fitnesse

### ISSUE THREAD

**Issue by haroon-sheikh** [fhoeben/hsac-fitnesse-fixtures#75]
Hi, 

I'm trying to use the https://github.com/fitnesse/fitnesse-git-plugin for recent changes with this but getting the following error

```bash
[INFO] --- exec-maven-plugin:1.4.0:exec (default-cli) @ fitnesse ---
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jgit/api/errors/GitAPIException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:191)
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:43)
	at fitnesse.components.ComponentFactory.createComponent(ComponentFactory.java:80)
	at fitnesse.ContextConfigurator.makeFitNesseContext(ContextConfigurator.java:106)
	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:69)
	at fitnesseMain.FitNesseMain.launchFitNesse(FitNesseMain.java:58)
	at fitnesseMain.FitNesseMain.main(FitNesseMain.java:38)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jgit.api.errors.GitAPIException
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 8 more
```

I have added `RecentChanges=fitnesse.wiki.fs.GitFileVersionsController` in `plugin.properties` but when I try to `mvn compile exec:exec`, I'm seeing the above error. Any advise on where I'm going wrong please?

**Comment by fhoeben** [comment]
It looks like your installation misses a .jar required by the fitnesse-git-plugin. I know there were some versions of fitnesse that bundled the jGit library, but they stopped doing that some versions ago.
Besides adding the line to the `plugin.properties` what else did you do to install the plugin? Did you place the plugin's jar in the plugins directory?

You probably need to add the 'jGit' jar to the plugins directory to address this problem. But you should really check with the maintainers of fitnesse-git-plugin how to address this problem. @amolenaar can you help him out?

**Comment by amolenaar** [comment]
Looks like you miss jgit.jar. I built the plugin in 2 flavors:

1. Just the plugin, use this when you use a build tool to start FitNesse (the preferred way IMHO)
2. use the `-all.jar` for standalone setups, jgit is included in the fitnesse plugin jar.

**Comment by fhoeben** [comment]
Easiest way to get the 'all' version in your project is probably to add the following lines (below the similar lines for maven-classpath-plugin):

```
								<artifactItem>
									<groupId>org.fitnesse.plugins</groupId>
									<artifactId>fitnesse-git-plugin</artifactId>
									<version>1.1.1</version>
									<classifier>all</classifier>
									<overWrite>true</overWrite>
								</artifactItem>
```

**Comment by amolenaar** [comment]
Just having the dependency when starting FitNesse is sufficient. There's no need to have jGit on the SUT's classpath (the classpath used to start Fit and Slim).

**Comment by fhoeben** [comment]
That's what the pom change I suggest would accomplish (I believe). The jar would be copied to the plugins directory (where FitNesse will pick it up), but no maven dependency is added (just like is done for the maven-classpath-plugin and the hsac-fitnesse-plugin).

**Comment by haroon-sheikh** [comment]
thanks @amolenaar @fhoeben 

As mentioned, I tried adding it as dependency. That didn't work, was missing the `jgit.jar`

But adding jar with all classifier within plugins fixed it for me.

```bash
<artifactItem>
    <groupId>org.fitnesse.plugins</groupId>
    <artifactId>fitnesse-git-plugin</artifactId>
    <version>1.1.1</version>
    <classifier>all</classifier>
    <overWrite>true</overWrite>
</artifactItem>
```
